
CREATE PROCEDURE dbo.Sets
AS
SET ANSI_NULLS  OFF
SET ANSI_PADDING OFF
SET ANSI_WARNINGS OFF
SET ARITHABORT OFF
SET NUMERIC_ROUNDABORT ON
SET QUOTED_IDENTIFIER OFF
SET CONCAT_NULL_YIELDS_NULL OFF

-- SRD0084, SRD0085, SRD0086, SRD0087, SRD0088, SRD0089
