// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SqlAnalyzerSsmsVsix
{
    internal sealed partial class Vsix
    {
        public const string Id = "SqlAnalyzerSsmsVsix.23bf40fc-9960-4dfa-bf04-3ba4a683b56e";
        public const string Name = "SqlAnalyzerSsmsVsix";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Erik Ejlskov Jensen";
        public const string Tags = "";
    }
}
