// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the free extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
using System;

namespace SqlAnalyzerSsmsVsix
{
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string SqlAnalyzerSsmsVsixString = "f865d6ab-4830-452a-b732-ec6a2a029b68";
        public static Guid SqlAnalyzerSsmsVsix = new Guid(SqlAnalyzerSsmsVsixString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
    }
}