// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SqlAnalyzerSsms
{
    internal sealed partial class Vsix
    {
        public const string Id = "SqlProjectsPowerTools.SSMS.D7DABDC8-FE46-4DA4-BED8-2EAF1A2A578D";
        public const string Name = "SQL Database Project Power Tools for SSMS";
        public const string Description = @"Tools to enhance the SQL Database Projects experience in SSMS, including import of existing databases, compare schemas, create E-R diagrams and much more.";
        public const string Language = "en-US";
        public const string Version = "1.0.0";
        public const string Author = "ErikEJ";
        public const string Tags = "";
        public const bool IsPreview = true;
    }
}
