// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SqlAnalyzerSsms
{
    internal sealed partial class Vsix
    {
        public const string Id = "TSqlAnalyzerSsms.f1322c34-dfaa-4842-8933-b439626da91d";
        public const string Name = "T-SQL Analyzer for SSMS";
        public const string Description = @"Live T-SQL static code analysis - checks for bad practices relating to design, naming, performance and security.";
        public const string Language = "en-US";
        public const string Version = "1.0.0";
        public const string Author = "ErikEJ";
        public const string Tags = "";
        public const bool IsPreview = false;
    }
}
