//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSQLSmellSCA {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TSQLSmellSCA.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create ResourceManager for {0} from {1}..
        /// </summary>
        internal static string CannotCreateResourceManager {
            get {
                return ResourceManager.GetString("CannotCreateResourceManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TSQLSmellSCA.Resources.
        /// </summary>
        internal static string ResourceBaseName {
            get {
                return ResourceManager.GetString("ResourceBaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid cross server joins.
        /// </summary>
        internal static string TSQLSmellRuleName01 {
            get {
                return ResourceManager.GetString("TSQLSmellRuleName01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best practice is to use two part naming.
        /// </summary>
        internal static string TSQLSmellRuleName02 {
            get {
                return ResourceManager.GetString("TSQLSmellRuleName02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirty Reads cause consistency errors.
        /// </summary>
        internal static string TSQLSmellRuleName03 {
            get {
                return ResourceManager.GetString("TSQLSmellRuleName03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dont Override the optimizer.
        /// </summary>
        internal static string TSQLSmellRuleName04 {
            get {
                return ResourceManager.GetString("TSQLSmellRuleName04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid use of &apos;Select *&apos;.
        /// </summary>
        internal static string TSQLSmellRuleName05 {
            get {
                return ResourceManager.GetString("TSQLSmellRuleName05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid Explicit Conversion of Columnar data.
        /// </summary>
        internal static string TSQLSmellRuleName06 {
            get {
                return ResourceManager.GetString("TSQLSmellRuleName06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid use of ordinal positions in ORDER BY Clauses.
        /// </summary>
        internal static string TSQLSmellRuleName07 {
            get {
                return ResourceManager.GetString("TSQLSmellRuleName07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dont Change DateFormat.
        /// </summary>
        internal static string TSQLSmellRuleName08 {
            get {
                return ResourceManager.GetString("TSQLSmellRuleName08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dont Change DateFirst.
        /// </summary>
        internal static string TSQLSmellRuleName09 {
            get {
                return ResourceManager.GetString("TSQLSmellRuleName09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadUnCommitted: Dirty reads can cause consistency errors.
        /// </summary>
        internal static string TSQLSmellRuleName10 {
            get {
                return ResourceManager.GetString("TSQLSmellRuleName10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single character aliases are poor practice.
        /// </summary>
        internal static string TSQLSmellRuleName11 {
            get {
                return ResourceManager.GetString("TSQLSmellRuleName11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Column specifications on insert.
        /// </summary>
        internal static string TSQLSmellRuleName12 {
            get {
                return ResourceManager.GetString("TSQLSmellRuleName12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONCAT_NULL_YIELDS_NULL should be on.
        /// </summary>
        internal static string TSQLSmellRuleName13 {
            get {
                return ResourceManager.GetString("TSQLSmellRuleName13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANSI_NULLS should be On.
        /// </summary>
        internal static string TSQLSmellRuleName14 {
            get {
                return ResourceManager.GetString("TSQLSmellRuleName14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANSI_PADDING should be On.
        /// </summary>
        internal static string TSQLSmellRuleName15 {
            get {
                return ResourceManager.GetString("TSQLSmellRuleName15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANSI_WARNINGS should be On.
        /// </summary>
        internal static string TSQLSmellRuleName16 {
            get {
                return ResourceManager.GetString("TSQLSmellRuleName16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARITHABORT should be On.
        /// </summary>
        internal static string TSQLSmellRuleName17 {
            get {
                return ResourceManager.GetString("TSQLSmellRuleName17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NUMERIC_ROUNDABORT should be Off.
        /// </summary>
        internal static string TSQLSmellRuleName18 {
            get {
                return ResourceManager.GetString("TSQLSmellRuleName18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUOTED_IDENTIFIER should be ON.
        /// </summary>
        internal static string TSQLSmellRuleName19 {
            get {
                return ResourceManager.GetString("TSQLSmellRuleName19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FORCEPLAN should be OFF.
        /// </summary>
        internal static string TSQLSmellRuleName20 {
            get {
                return ResourceManager.GetString("TSQLSmellRuleName20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use 2 part naming in EXECUTE statements.
        /// </summary>
        internal static string TSQLSmellRuleName21 {
            get {
                return ResourceManager.GetString("TSQLSmellRuleName21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity value should be agnostic.
        /// </summary>
        internal static string TSQLSmellRuleName22 {
            get {
                return ResourceManager.GetString("TSQLSmellRuleName22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid single line comments.
        /// </summary>
        internal static string TSQLSmellRuleName23 {
            get {
                return ResourceManager.GetString("TSQLSmellRuleName23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use two part naming.
        /// </summary>
        internal static string TSQLSmellRuleName24 {
            get {
                return ResourceManager.GetString("TSQLSmellRuleName24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RANGE windows are much slower then ROWS (Explicit use).
        /// </summary>
        internal static string TSQLSmellRuleName25 {
            get {
                return ResourceManager.GetString("TSQLSmellRuleName25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RANGE windows are much slower then ROWS (Implicit use).
        /// </summary>
        internal static string TSQLSmellRuleName26 {
            get {
                return ResourceManager.GetString("TSQLSmellRuleName26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create table statements should specify schema.
        /// </summary>
        internal static string TSQLSmellRuleName27 {
            get {
                return ResourceManager.GetString("TSQLSmellRuleName27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordering in a view does not guarantee result set ordering.
        /// </summary>
        internal static string TSQLSmellRuleName28 {
            get {
                return ResourceManager.GetString("TSQLSmellRuleName28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursors default to writable.  Specify FAST_FORWARD.
        /// </summary>
        internal static string TSQLSmellRuleName29 {
            get {
                return ResourceManager.GetString("TSQLSmellRuleName29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include SET NOCOUNT ON inside stored procedures.
        /// </summary>
        internal static string TSQLSmellRuleName30 {
            get {
                return ResourceManager.GetString("TSQLSmellRuleName30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXISTS/NOT EXISTS can be more performant than COUNT(*).
        /// </summary>
        internal static string TSQLSmellRuleName31 {
            get {
                return ResourceManager.GetString("TSQLSmellRuleName31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordering in a derived table does not guarantee result set ordering.
        /// </summary>
        internal static string TSQLSmellRuleName32 {
            get {
                return ResourceManager.GetString("TSQLSmellRuleName32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single character variable names are poor practice.
        /// </summary>
        internal static string TSQLSmellRuleName33 {
            get {
                return ResourceManager.GetString("TSQLSmellRuleName33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression used with TOP should be wrapped in parenthises.
        /// </summary>
        internal static string TSQLSmellRuleName34 {
            get {
                return ResourceManager.GetString("TSQLSmellRuleName34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOP(100) percent is ignored by the optimizer.
        /// </summary>
        internal static string TSQLSmellRuleName35 {
            get {
                return ResourceManager.GetString("TSQLSmellRuleName35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreign Key Constraints should be named.
        /// </summary>
        internal static string TSQLSmellRuleName36 {
            get {
                return ResourceManager.GetString("TSQLSmellRuleName36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Constraints should be named.
        /// </summary>
        internal static string TSQLSmellRuleName37 {
            get {
                return ResourceManager.GetString("TSQLSmellRuleName37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Key Constraints on temporary tables should not be named.
        /// </summary>
        internal static string TSQLSmellRuleName38 {
            get {
                return ResourceManager.GetString("TSQLSmellRuleName38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Constraints on temporary tables should not be named.
        /// </summary>
        internal static string TSQLSmellRuleName39 {
            get {
                return ResourceManager.GetString("TSQLSmellRuleName39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreign Key Constraints on temporary tables should not be named.
        /// </summary>
        internal static string TSQLSmellRuleName40 {
            get {
                return ResourceManager.GetString("TSQLSmellRuleName40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Constraints on temporary tables should not be named.
        /// </summary>
        internal static string TSQLSmellRuleName41 {
            get {
                return ResourceManager.GetString("TSQLSmellRuleName41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use of SET ROWCOUNT is deprecated : use TOP.
        /// </summary>
        internal static string TSQLSmellRuleName42 {
            get {
                return ResourceManager.GetString("TSQLSmellRuleName42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potential SQL Injection Issue.
        /// </summary>
        internal static string TSQLSmellRuleName43 {
            get {
                return ResourceManager.GetString("TSQLSmellRuleName43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dont override the optimizer ( FORCESCAN ).
        /// </summary>
        internal static string TSQLSmellRuleName44 {
            get {
                return ResourceManager.GetString("TSQLSmellRuleName44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dont override the optimizer ( Index Hint).
        /// </summary>
        internal static string TSQLSmellRuleName45 {
            get {
                return ResourceManager.GetString("TSQLSmellRuleName45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;= Null&quot; Comparison.
        /// </summary>
        internal static string TSQLSmellRuleName46 {
            get {
                return ResourceManager.GetString("TSQLSmellRuleName46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use of deprecated data type.
        /// </summary>
        internal static string TSQLSmellRuleName47 {
            get {
                return ResourceManager.GetString("TSQLSmellRuleName47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TSQLSmellRuleName48.
        /// </summary>
        internal static string TSQLSmellRuleName48 {
            get {
                return ResourceManager.GetString("TSQLSmellRuleName48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TSQLSmellRuleName49.
        /// </summary>
        internal static string TSQLSmellRuleName49 {
            get {
                return ResourceManager.GetString("TSQLSmellRuleName49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TSQLSmellRuleName50.
        /// </summary>
        internal static string TSQLSmellRuleName50 {
            get {
                return ResourceManager.GetString("TSQLSmellRuleName50", resourceCulture);
            }
        }
    }
}
