name: CLI Pipeline

on:
  workflow_dispatch:

permissions:
  id-token: write  # enable GitHub OIDC token issuance for this job

env:
  VERSION: ${{ github.run_number }}

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: "10.0.x" # SDK Version to use

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v3

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Package CLI Lib
        if: startsWith(github.ref, 'refs/heads/master') && github.repository_owner == 'ErikEJ'
        run: dotnet pack tools/ErikEJ.DacFX.TSQLAnalyzer/ErikEJ.DacFX.TSQLAnalyzer.csproj -p:PackageVersion=1.0.${{ env.VERSION }} -p:InformationalVersion=1.0.${{ env.VERSION }}

      - name: Package CLI
        if: startsWith(github.ref, 'refs/heads/master') && github.repository_owner == 'ErikEJ'
        run: dotnet pack tools/SqlAnalyzerCli/SqlAnalyzerCli.csproj -p:PackageVersion=1.0.${{ env.VERSION }} -p:InformationalVersion=1.0.${{ env.VERSION }}

      - name: NuGet login (OIDC => temp API key)
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}
    
      - name: Publish NuGet
        if: startsWith(github.ref, 'refs/heads/master') && github.repository_owner == 'ErikEJ'
        run: dotnet nuget push **\*.nupkg --source 'https://api.nuget.org/v3/index.json' --api-key ${{steps.login.outputs.NUGET_API_KEY}} --skip-duplicate
