name: CLI Pipeline

on:
  workflow_dispatch:

env:
  VERSION: ${{ github.run_number }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x" # SDK Version to use

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Package CLI Lib
        if: startsWith(github.ref, 'refs/heads/master') && github.repository_owner == 'ErikEJ'
        run: dotnet pack tools/ErikEJ.DacFX.TSQLAnalyzer/ErikEJ.DacFX.TSQLAnalyzer.csproj -p:PackageVersion=1.0.${{ env.VERSION }} -p:InformationalVersion=1.0.${{ env.VERSION }}

      - name: Package CLI
        if: startsWith(github.ref, 'refs/heads/master') && github.repository_owner == 'ErikEJ'
        run: dotnet pack tools/SqlAnalyzerCli/SqlAnalyzerCli.csproj -p:PackageVersion=1.0.${{ env.VERSION }} -p:InformationalVersion=1.0.${{ env.VERSION }}

      - name: Publish NuGet
        if: startsWith(github.ref, 'refs/heads/master') && github.repository_owner == 'ErikEJ'
        run: dotnet nuget push **\*.nupkg --source 'https://api.nuget.org/v3/index.json' --api-key ${{ secrets.NUGET }} --skip-duplicate
