name: .NET Library Publish

on:
  workflow_dispatch:

permissions:
  id-token: write # This is required for the federated credential to work

env:
  VERSION: ${{ github.run_number }}

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.0.x" # SDK Version to use

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Run Unit Tests
        run: dotnet test --no-build --configuration Release --verbosity normal

      - name: Azure CLI login with federated credential
        if: github.event_name != 'pull_request'
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Install dotnet sign
        if: github.event_name != 'pull_request'
        run: dotnet tool install --global sign --prerelease

      - name: Sign .dll files
        if: github.ref == 'refs/heads/master' && github.repository_owner == 'erikej' && github.event_name == 'workflow_dispatch'
        run: sign code artifact-signing `
          ./src/SqlServer.TSQLSmells/bin/Release/net472/TSQLSmellSCA.dll `
          ./src/SqlServer.TSQLSmells/bin/Release/netstandard2.1/TSQLSmellSCA.dll `
          ./src/SqlServer.Rules/bin/Release/net472/SqlServer.Rules.dll `
          ./src/SqlServer.Rules/bin/Release/netstandard2.1/SqlServer.Rules.dll `
          --artifact-signing-account ErikEJ `
          --artifact-signing-certificate-profile ErikEJCert `
          --artifact-signing-endpoint https://weu.codesigning.azure.net `
          --verbosity warning

      - name: Pack
        run: dotnet pack ./src/SqlServer.Rules/SqlServer.Rules.csproj --no-build --configuration Release

      - name: Pack
        run: dotnet pack ./src/SqlServer.TSQLSmells/TSQLSmellSCA.csproj --no-build --configuration Release

      - name: Publish artifacts
        if: github.ref == 'refs/heads/master' && github.repository_owner == 'erikej' && (github.event_name == 'push' ||  github.event_name == 'workflow_dispatch')
        uses: actions/upload-artifact@v7
        with:
          name: Artifacts
          path: |
            **/*.nupkg

      - name: Publish NuGet
        if: startsWith(github.ref, 'refs/heads/master') && github.repository_owner == 'ErikEJ'
        run: dotnet nuget push **\*.nupkg --source 'https://api.nuget.org/v3/index.json' --api-key ${{ secrets.NUGET }} --skip-duplicate
